-- AlterTable
ALTER TABLE "ActivationCode" ADD COLUMN     "maxProducts" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "maxUsers" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "plan" TEXT NOT NULL DEFAULT 'STARTER';

-- AlterTable
ALTER TABLE "Company" ADD COLUMN     "maxProducts" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "maxUsers" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "plan" TEXT NOT NULL DEFAULT 'STARTER',
ADD COLUMN     "subscriptionStatus" TEXT NOT NULL DEFAULT 'ACTIVE';
