export const PERMISSIONS = {
  ADD_PRODUCT: 'ADD_PRODUCT',
  VIEW_STOCK: 'VIEW_STOCK',
  SCAN_IN: 'SCAN_IN',
  SCAN_OUT: 'SCAN_OUT',
  MANAGE_USERS: 'MANAGE_USERS',
  ADD_ASSET: 'ADD_ASSET',
  VIEW_ASSET: 'VIEW_ASSET',
  EDIT_ASSET: 'EDIT_ASSET',
  DELETE_ASSET: 'DELETE_ASSET'
};