/**
 * @file permissions.ts
 * @description Application permission constants.
 * Defines all available permissions used for role-based access control (RBAC).
 */

export const PERMISSIONS = {
  // PRODUCTS
  ADD_PRODUCT: 'ADD_PRODUCT',
  VIEW_STOCK: 'VIEW_STOCK',
  SCAN_IN: 'SCAN_IN',
  SCAN_OUT: 'SCAN_OUT',

  // USERS
  MANAGE_USERS: 'MANAGE_USERS',

  // ASSETS
  ADD_ASSET: 'ADD_ASSET',
  VIEW_ASSET: 'VIEW_ASSET',
  EDIT_ASSET: 'EDIT_ASSET',
  DELETE_ASSET: 'DELETE_ASSET',

  // TRUCK STOCK
  VIEW_ASSIGNED_TRUCK_STOCK: 'VIEW_ASSIGNED_TRUCK_STOCK',
  UPLOAD_RECEIPT: 'UPLOAD_RECEIPT',
  VIEW_LOW_STOCK_ALERTS: 'VIEW_LOW_STOCK_ALERTS',

  MANAGE_TRUCK_STOCK: 'MANAGE_TRUCK_STOCK',
  ASSIGN_TRUCK_STOCK: 'ASSIGN_TRUCK_STOCK',
  APPROVE_RECEIPTS: 'APPROVE_RECEIPTS',
  VIEW_ALL_TRUCKS: 'VIEW_ALL_TRUCKS',
  VIEW_TRUCK_STOCK: 'VIEW_TRUCK_STOCK',
  TRANSFER_STOCK_TO_TRUCK: 'TRANSFER_STOCK_TO_TRUCK'
} as const;